### ISSUE TITLE
Docker ARM Version + Config Directory

### ISSUE THREAD

**Issue by Jiriteach** [zimbres/UptimeKumaRemoteProbe#2]
Hi - Thanks for the this remote probe. 
Have set it up on a dev Windows environment using Docker and it works well.

Wondered if you are able to compile a ARM version for Docker which can be used on a Raspberry PI? 
I did see the in release .zip there was a linux ARM but how would one install or run this on a Raspberry Pi? 

Also any chance of a configuration directory to make it easier to manage the appsettings.json?

Thanks

**Comment by zimbres** [comment]
Hi @Jiriteach 

I realized that the Linux Arm folder is published with the same target as Linux folder, I will correct this, but the Windows folder is set to target "Portable", so, this should run on any platform, you just need to run "dotnet UptimeKumaRemoteProbe.dll"

Once I upload a new release with correct target for Arm version, you should be able to run it but just chmod +x and then ./UptimeKumaRemoteProbe.

Can you explain a little more this configuration directory?

Regards,

**Comment by Jiriteach** [comment]
> Hi @Jiriteach
> 
> I realized that the Linux Arm folder is published with the same target as Linux folder, I will correct this, but the Windows folder is set to target "Portable", so, this should run on any platform, you just need to run "dotnet UptimeKumaRemoteProbe.dll"
> 
> Once I upload a new release with correct target for Arm version, you should be able to run it but just chmod +x and then ./UptimeKumaRemoteProbe.
> 
> Can you explain a little more this configuration directory?
> 
> Regards,

Thanks

Docker would be the easiest approch if built for ARM. Super easy to launch and no needing any extra components.
You can mount a host directory onto the container - https://docs.docker.com/storage/volumes.

So the container reads appsettings.json from host directory and it makes it easy for someone to edit appsettings.json without needing to go into the container to make changes. Also since appsettings.json will be on the host - its always there is case the container is recreating etc.
The setting for say DATA could be part of the container startup.

**Comment by zimbres** [comment]
@Jiriteach 

Hi you can bind a host file in the container:

docker run -d --name ukrp --mount type=bind,source="$(pwd)"/appsettings.json,target=/app/appsettings.json zimbres/uptime-kuma-remote-probe

I need to realize how to build this Arm/V7 container in a Amd64 machine. For RPi 64, I think image Arm64 should work.

**Comment by Jiriteach** [comment]
> @Jiriteach
> 
> Hi you can bind a host file in the container:
> 
> docker run -d --name ukrp --mount type=bind,source="$(pwd)"/appsettings.json,target=/app/appsettings.json zimbres/uptime-kuma-remote-probe
> 
> I need to realize how to build this Arm/V7 container in a Amd64 machine. For RPi 64, I think image Arm64 should work.

Thanks for the pointer on binding to the host. 

Tried using Docker Desktop and buildx to build for Arm/v7? - https://docs.docker.com/desktop/multi-arch/#build-and-run-multi-architecture-images.

Arm/V7 would be perfect as I can run these on my RPI's.

**Comment by zimbres** [comment]
@Jiriteach 

Can you try this "dev" tag please? I dont have a RPi to test it here.

https://hub.docker.com/r/zimbres/uptime-kuma-remote-probe/tags

**Comment by Jiriteach** [comment]
> @Jiriteach
> 
> Can you try this "dev" tag please? I dont have a RPi to test it here.
> 
> https://hub.docker.com/r/zimbres/uptime-kuma-remote-probe/tags

Perfect - Thanks. Yes this works really well. Running on one of my RPI 4's. 
Not configured yet but simple launch!

Will try binding to the host and should be away!

<img width="1172" alt="Screen Shot 2022-07-05 at 16 12 55" src="https://user-images.githubusercontent.com/2116446/177248105-8473c10d-e988-4c27-8354-40d1b60fc974.png">
