### ISSUE TITLE
Multiple Configurations - Possible?

### ISSUE THREAD

**Issue by Jiriteach** [zimbres/UptimeKumaRemoteProbe#7]
Hi - I was wondering if it is possible to have multiple configurations? If so - whats the syntax?
So multiple remote probes against a since Uptime Kuma instance.

Thanks

**Comment by zimbres** [comment]
Hi, yes it is.

You need to set the probe name in the appsettings.json on field Configurations -> ProbeName.

Than use this in the TAGs on UK:

![image](https://github.com/zimbres/UptimeKumaRemoteProbe/assets/29772043/6cee8edb-8804-4936-b9d1-3f665a86adf5)

The remote probe will look for the TAG "Probe" that match the ProbeName in appsettings.

**Comment by Jiriteach** [comment]
Thanks. What's the syntax for appsettings.json. Just comma delimited for the configuration?

**Comment by zimbres** [comment]
Appsettings is a json file, the relevant part of configuration is the section "Configurations"

```
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    },
    "Console": {
      "LogLevel": {
        "Default": "Information",
        "Microsoft": "Warning",
        "Microsoft.Hosting.Lifetime": "Information"
      },
      "FormatterName": "json",
      "FormatterOptions": {
        "SingleLine": true,
        "IncludeScopes": false,
        "TimestampFormat": "dd/MM/yyyy HH:mm:ss",
        "UseUtcTimestamp": false,
        "JsonWriterOptions": {
          "Indented": false
        }
      }
    }
  },
  "Configurations": {
    "Url": "http://localhost:3001/",
    "Username": "admin",
    "Password": "Admin123",
    "ProbeName": "Home",
    "UpDependency": "192.168.1.1",
    "Timeout": 1000,
    "Delay": 60000,
    "ConnectionStrings": {
      "PGSQL": "Host=localhost;Database=postgres;Username=postgres;Password=postgres"
    },
    "WhoisApiUrl": "https://whoisjson.com/api/v1/whois?domain=keep.this&format=json",
    "WhoisApiToken": "whoisjsonApiToken"
  }
}
```

**Comment by Jiriteach** [comment]
Thanks - whoops sorry I realised I asked my question incorrectly, is it possible to have 1 remote probe against multiple instances of Uptime Kuma? So the in the appsettings.json - there are two configurations. One configuration for url1 and another for url2.

I have two instances of Uptime Kuma - externally hosted and internally hosted and want to configure one of the remote probes to talk to both. Is this possible? Thanks

**Comment by zimbres** [comment]
No, this is not possible, to achieve this you need two different probes.

**Comment by Jiriteach** [comment]
Thanks for confirming.

**Comment by wuyoujiana** [comment]
I would like to ask, can multiple types be configured within a single probe? Or can a single type be configured with multiple addresses, such as Website A and Website B?

**Comment by zimbres** [comment]
Yes, multiple types and multiple addresses can be set on a single probe.

Example:

![image](https://github.com/user-attachments/assets/23a56e2e-6af4-4533-8fee-5fcad3ac1851)
